all:
	ln -sf $(shell pwd)/git-email.py /usr/local/bin/git-email
	ln -sf $(shell pwd)/git-patchs.py /usr/local/bin/git-patchs
	ln -sf $(shell pwd)/git-ack.py /usr/local/bin/git-ack
	ln -sf $(shell pwd)/patch-back.py /usr/local/bin/patch-back
